In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import lightkurve as lk
import time

c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\lightkurve\prf\__init__.py:7: UserWarning: Warning: the tpfmodel submodule is not available without oktopus installed, which requires a current version of autograd. See #1452 for details.
  warnings.warn(

In [3]:
PROJECT_ROOT = Path.cwd().parent

CSV_PATH = PROJECT_ROOT / "cumulative_2026.08.12_23.25.19.csv"
FITS_DIR = PROJECT_ROOT / "data" / "raw" / "fits"

FITS_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("CSV path:", CSV_PATH)
print("FITS directory:", FITS_DIR)

Project root: d:\exoplanet-astro
CSV path: d:\exoplanet-astro\cumulative_2026.08.12_23.25.19.csv
FITS directory: d:\exoplanet-astro\data\raw\fits

In [4]:
print("CSV exists:", CSV_PATH.exists())

CSV exists: True

In [5]:
with open(CSV_PATH, "r", encoding="utf-8") as f:
    for i in range(20):
        print(i, repr(f.readline().strip()))

0 '# This file was produced by the NASA Exoplanet Archive  http://exoplanetarchive.ipac.caltech.edu'
1 '# Wed Aug 12 23:25:19 2026'
2 '#'
3 '# COLUMN kepid:          KepID'
4 '# COLUMN kepoi_name:     KOI Name'
5 '# COLUMN kepler_name:    Kepler Name'
6 '# COLUMN koi_disposition: Exoplanet Archive Disposition'
7 '# COLUMN koi_vet_stat:   Vetting Status'
8 '# COLUMN koi_vet_date:   Date of Last Parameter Update'
9 '# COLUMN koi_pdisposition: Disposition Using Kepler Data'
10 '# COLUMN koi_score:      Disposition Score'
11 '# COLUMN koi_fpflag_nt:  Not Transit-Like False Positive Flag'
12 '# COLUMN koi_fpflag_ss:  Stellar Eclipse False Positive Flag'
13 '# COLUMN koi_fpflag_co:  Centroid Offset False Positive Flag'
14 '# COLUMN koi_fpflag_ec:  Ephemeris Match Indicates Contamination False Positive Flag'
15 '# COLUMN koi_disp_prov:  Disposition Provenance'
16 '# COLUMN koi_comment:    Comment'
17 '# COLUMN koi_period:     Orbital Period [days]'
18 '# COLUMN koi_period_err1: Orbital Period Upper Unc. [days]'
19 '# COLUMN koi_period_err2: Orbital Period Lower Unc. [days]'

In [6]:
with open(CSV_PATH, "r", encoding="utf-8-sig") as f:
    for i, line in enumerate(f):
        if "kepid" in line and "kepoi_name" in line and "koi_disposition" in line:
            print("Header found at line:", i)
            print(line.strip())
            break

Header found at line: 144
rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_vet_stat,koi_vet_date,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_disp_prov,koi_comment,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,koi_time0,koi_time0_err1,koi_time0_err2,koi_eccen,koi_eccen_err1,koi_eccen_err2,koi_longp,koi_longp_err1,koi_longp_err2,koi_impact,koi_impact_err1,koi_impact_err2,koi_duration,koi_duration_err1,koi_duration_err2,koi_ingress,koi_ingress_err1,koi_ingress_err2,koi_depth,koi_depth_err1,koi_depth_err2,koi_ror,koi_ror_err1,koi_ror_err2,koi_srho,koi_srho_err1,koi_srho_err2,koi_fittype,koi_prad,koi_prad_err1,koi_prad_err2,koi_sma,koi_sma_err1,koi_sma_err2,koi_incl,koi_incl_err1,koi_incl_err2,koi_teq,koi_teq_err1,koi_teq_err2,koi_insol,koi_insol_err1,koi_insol_err2,koi_dor,koi_dor_err1,koi_dor_err2,koi_limbdark_mod,koi_ldm_coeff4,koi_ldm_coeff3,koi_ldm_coeff2,koi_ldm_coeff1,koi_parm_prov,koi_max_sngle_ev,koi_max_mult_ev,koi_model_snr,koi_count,koi_num_transits,koi_tce_plnt_num,koi_tce_delivname,koi_quarters,koi_bin_oedp_sig,koi_trans_mod,koi_model_dof,koi_model_chisq,koi_datalink_dvr,koi_datalink_dvs,koi_steff,koi_steff_err1,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_smet,koi_smet_err1,koi_smet_err2,koi_srad,koi_srad_err1,koi_srad_err2,koi_smass,koi_smass_err1,koi_smass_err2,koi_sage,koi_sage_err1,koi_sage_err2,koi_sparprov,ra,dec,koi_kepmag,koi_gmag,koi_rmag,koi_imag,koi_zmag,koi_jmag,koi_hmag,koi_kmag,koi_fwm_stat_sig,koi_fwm_sra,koi_fwm_sra_err,koi_fwm_sdec,koi_fwm_sdec_err,koi_fwm_srao,koi_fwm_srao_err,koi_fwm_sdeco,koi_fwm_sdeco_err,koi_fwm_prao,koi_fwm_prao_err,koi_fwm_pdeco,koi_fwm_pdeco_err,koi_dicco_mra,koi_dicco_mra_err,koi_dicco_mdec,koi_dicco_mdec_err,koi_dicco_msky,koi_dicco_msky_err,koi_dikco_mra,koi_dikco_mra_err,koi_dikco_mdec,koi_dikco_mdec_err,koi_dikco_msky,koi_dikco_msky_err

In [7]:
df = pd.read_csv(CSV_PATH, skiprows=144)

print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

Shape: (9564, 141)

First 5 rows:

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_vet_stat,koi_vet_date,koi_pdisposition,koi_score,koi_fpflag_nt,...,koi_dicco_mdec,koi_dicco_mdec_err,koi_dicco_msky,koi_dicco_msky_err,koi_dikco_mra,koi_dikco_mra_err,koi_dikco_mdec,koi_dikco_mdec_err,koi_dikco_msky,koi_dikco_msky_err
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,Done,2018-08-16,CANDIDATE,1.000,0,...,0.200,0.160,0.200,0.170,0.080,0.130,0.310,0.170,0.320,0.160
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,Done,2018-08-16,CANDIDATE,0.969,0,...,0.000,0.480,0.390,0.360,0.490,0.340,0.120,0.730,0.500,0.450
2,3,10811496,K00753.01,NaN,CANDIDATE,Done,2018-08-16,CANDIDATE,0.000,0,...,-0.034,0.070,0.042,0.072,0.002,0.071,-0.027,0.074,0.027,0.074
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,Done,2018-08-16,FALSE POSITIVE,0.000,0,...,0.147,0.078,0.289,0.079,-0.257,0.072,0.099,0.077,0.276,0.076
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,Done,2018-08-16,CANDIDATE,1.000,0,...,-0.090,0.180,0.100,0.140,0.070,0.180,0.020,0.160,0.070,0.200

In [8]:
print("KIC column exists:", "kepid" in df.columns)
print("Disposition column exists:", "koi_disposition" in df.columns)

print("\nUnique KIC IDs:", df["kepid"].nunique())
print("Missing KIC IDs:", df["kepid"].isna().sum())

print("\nDisposition counts:")
print(df["koi_disposition"].value_counts())

KIC column exists: True
Disposition column exists: True

Unique KIC IDs: 8214
Missing KIC IDs: 0

Disposition counts:
koi_disposition
FALSE POSITIVE    4839
CONFIRMED         2747
CANDIDATE         1978
Name: count, dtype: int64

In [9]:
kic_ids = (
    df["kepid"]
    .dropna()
    .astype(int)
    .drop_duplicates()
    .tolist()
)

print("Total unique KIC IDs:", len(kic_ids))
print("First 10 IDs:", kic_ids[:10])

Total unique KIC IDs: 8214
First 10 IDs: [10797460, 10811496, 10848459, 10854555, 10872983, 6721123, 10910878, 11446443, 10666592, 6922244]

In [10]:
kic_ids = sorted(kic_ids)

mid = len(kic_ids) // 2

jhalak_ids = kic_ids[:mid]
gayatri_ids = kic_ids[mid:]

print("Total IDs:", len(kic_ids))
print("Jhalak's IDs:", len(jhalak_ids))
print("Gayatri's IDs:", len(gayatri_ids))

print("\nJhalak's ID range:", jhalak_ids[0], "to", jhalak_ids[-1])
print("Gayatri's ID range:", gayatri_ids[0], "to", gayatri_ids[-1])

Total IDs: 8214
Jhalak's IDs: 4107
Gayatri's IDs: 4107

Jhalak's ID range: 757450 to 7887791
Gayatri's ID range: 7887890 to 12935144

In [11]:
METADATA_DIR = PROJECT_ROOT / "data" / "raw" / "metadata"
METADATA_DIR.mkdir(parents=True, exist_ok=True)

jhalak_ids_path = METADATA_DIR / "jhalak_kic_ids.csv"
gayatri_ids_path = METADATA_DIR / "gayatri_kic_ids.csv"

pd.DataFrame({"kepid": jhalak_ids}).to_csv(
    jhalak_ids_path,
    index=False
)

pd.DataFrame({"kepid": gayatri_ids}).to_csv(
    gayatri_ids_path,
    index=False
)

print("Jhalak's IDs saved to:", jhalak_ids_path)
print("Gayatri's IDs saved to:", gayatri_ids_path)

Jhalak's IDs saved to: d:\exoplanet-astro\data\raw\metadata\jhalak_kic_ids.csv
Gayatri's IDs saved to: d:\exoplanet-astro\data\raw\metadata\gayatri_kic_ids.csv

In [12]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

FITS_DIR = PROJECT_ROOT / "data" / "raw" / "fits"
TEMP_DIR = PROJECT_ROOT / "data" / "raw" / "mast_temp"
METADATA_DIR = PROJECT_ROOT / "data" / "raw" / "metadata"

print("Project root:", PROJECT_ROOT)

print("\nFITS directory:")
print(FITS_DIR)
print("Exists:", FITS_DIR.exists())

if FITS_DIR.exists():
    fits_files = list(FITS_DIR.rglob("*.fits"))
    print("FITS files found:", len(fits_files))

    for f in fits_files[:20]:
        print(f)

print("\nTemporary directory:")
print(TEMP_DIR)
print("Exists:", TEMP_DIR.exists())

if TEMP_DIR.exists():
    temp_files = [
        f for f in TEMP_DIR.rglob("*")
        if f.is_file()
    ]

    print("Temporary files found:", len(temp_files))

    for f in temp_files[:20]:
        print(f)

Project root: d:\exoplanet-astro

FITS directory:
d:\exoplanet-astro\data\raw\fits
Exists: True
FITS files found: 41503
d:\exoplanet-astro\data\raw\fits\kplr000757450-2009166043257_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2009259160929_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2009350155506_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2010078095331_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2010174085026_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2010265121752_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2010355172524_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2011073133259_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2011177032512_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2011208035123_slc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2011240104155_slc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2011271113734_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2011271113734_slc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2011303113607_slc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2011334093404_slc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2012004120508_llc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2012004120508_slc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2012032013838_slc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2012060035710_slc.fits
d:\exoplanet-astro\data\raw\fits\kplr000757450-2012088054726_llc.fits

Temporary directory:
d:\exoplanet-astro\data\raw\mast_temp
Exists: True
Temporary files found: 522
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\Kepler\kplr006032920_sc_Q000000000000003000\kplr006032920-2012277125453_slc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q01_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q01_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q02_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q02_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q03_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q03_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q04_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q04_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q05_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q05_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q06_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q06_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q07_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q07_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q08_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q08_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q09_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q09_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q10_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q10_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q11_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q11_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q12_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q12_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q13_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q13_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q14_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q14_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q15_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q15_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q16_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q16_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q17_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q17_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-stitched_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-stitched_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002437060-q01_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002437060-q01_kepler_v1.0_lc.fits

In [13]:
from pathlib import Path
from astropy.io import fits

temp_fits = list(TEMP_DIR.rglob("*.fits"))

print("Total FITS files in TEMP_DIR:", len(temp_fits))

# Count by parent/source folder
source_counts = {}

for file in temp_fits:
    parts = file.parts

    if "mastDownload" in parts:
        idx = parts.index("mastDownload")

        if idx + 1 < len(parts):
            source = parts[idx + 1]
        else:
            source = "unknown"
    else:
        source = "unknown"

    source_counts[source] = source_counts.get(source, 0) + 1

print("\nFiles by source:")
for source, count in source_counts.items():
    print(f"{source}: {count}")

# Check file sizes
total_bytes = sum(file.stat().st_size for file in temp_fits)

print(
    f"\nTotal size: "
    f"{total_bytes / (1024**3):.2f} GB"
)

print(
    f"Average size: "
    f"{total_bytes / len(temp_fits) / (1024**2):.2f} MB"
)

# Show first 20 files
print("\nFirst 20 FITS files:")
for file in temp_fits[:20]:
    print(file)

Total FITS files in TEMP_DIR: 522

Files by source:
Kepler: 1
HLSP: 521

Total size: 0.09 GB
Average size: 0.17 MB

First 20 FITS files:
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\Kepler\kplr006032920_sc_Q000000000000003000\kplr006032920-2012277125453_slc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q01_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q01_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q02_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q02_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q03_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q03_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q04_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q04_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q05_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q05_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q06_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q06_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q07_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q07_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q08_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q08_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q09_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q09_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q10_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q10_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q11_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q11_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q12_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q12_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q13_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q13_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q14_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q14_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q15_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q15_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q16_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q16_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-q17_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-q17_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002436378-stitched_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002436378-stitched_kepler_v1.0_lc.fits
d:\exoplanet-astro\data\raw\mast_temp\mastDownload\HLSP\hlsp_iris_kepler_kepler_kplr002437060-q01_kepler_v1.0_lc\hlsp_iris_kepler_kepler_kplr002437060-q01_kepler_v1.0_lc.fits

In [14]:
# Inspect what Lightkurve returns for one KIC

test_kic = 1870398

search_result = lk.search_lightcurve(
    f"KIC {test_kic}",
    mission="Kepler"
)

print("Total products returned:", len(search_result))

display(search_result.table)

Total products returned: 17

<Table length=17>
intentType obs_collection provenance_name ...   #     year sort_order
                                          ...
   str7         str6           str10      ... object int64   int64
---------- -------------- --------------- ... ------ ----- ----------
   science         Kepler          Kepler ...   None  2009          1
   science         Kepler          Kepler ...   None  2009          1
   science         Kepler          Kepler ...   None  2009          1
   science         Kepler          Kepler ...   None  2010          1
   science         Kepler          Kepler ...   None  2010          1
   science         Kepler          Kepler ...   None  2010          1
   science         Kepler          Kepler ...   None  2010          1
   science         Kepler          Kepler ...   None  2011          1
   science         Kepler          Kepler ...   None  2011          1
   science         Kepler          Kepler ...   None  2011          1
   science         Kepler          Kepler ...   None  2012          1
   science         Kepler          Kepler ...   None  2012          1
   science         Kepler          Kepler ...   None  2012          1
   science         Kepler          Kepler ...   None  2012          1
   science         Kepler          Kepler ...   None  2013          1
   science         Kepler          Kepler ...   None  2013          1
   science         Kepler          Kepler ...   None  2013          1

In [15]:
from collections import Counter

print(Counter(search_result.table["author"].tolist()))

Counter({'Kepler': 17})

In [16]:
def download_kic_products(kic, max_retries=3):
    """
    Download all available RAW Kepler science light-curve FITS products
    for one KIC.

    Keeps both Long Cadence and Short Cadence products.
    Does NOT download HLSP products.
    Does NOT preprocess or modify FITS files.

    Existing final FITS files are skipped.
    Failed downloads are retried.
    """

    kic = int(kic)

    try:
        # ---------------------------------------------------------
        # 1. Search MAST for this KIC
        # ---------------------------------------------------------

        search_result = lk.search_lightcurve(
            f"KIC {kic}",
            mission="Kepler"
        )

        # ---------------------------------------------------------
        # 2. Keep ONLY actual Kepler products
        # ---------------------------------------------------------

        authors = search_result.table["author"]

        kepler_mask = [
            str(author) == "Kepler"
            for author in authors
        ]

        kepler_products = search_result[kepler_mask]

        products_found = len(kepler_products)

        if products_found == 0:
            return {
                "kepid": kic,
                "status": "no_data",
                "products_found": 0,
                "products_downloaded": 0,
                "failed_products": 0
            }

        products_downloaded = 0
        failed_products = 0

        # ---------------------------------------------------------
        # 3. Download every Kepler product
        # ---------------------------------------------------------

        for i in range(products_found):

            data_uri = str(
                kepler_products.table["dataURI"][i]
            )

            filename = data_uri.split("/")[-1]

            final_path = FITS_DIR / filename

            # -----------------------------------------------------
            # Already downloaded?
            # -----------------------------------------------------

            if (
                final_path.exists()
                and final_path.stat().st_size > 0
            ):
                print(f"Already exists: {filename}")

                products_downloaded += 1
                continue

            success = False

            # -----------------------------------------------------
            # Retry download
            # -----------------------------------------------------

            for attempt in range(1, max_retries + 1):

                try:

                    print(
                        f"KIC {kic} | "
                        f"Product {i + 1}/{products_found} | "
                        f"Attempt {attempt}/{max_retries}"
                    )

                    # -------------------------------------------------
                    # Remove ONLY an incomplete copy of THIS filename
                    # from TEMP_DIR before retrying.
                    # -------------------------------------------------

                    old_temp_files = list(
                        TEMP_DIR.rglob(filename)
                    )

                    for old_file in old_temp_files:

                        try:
                            old_file.unlink()

                        except Exception:
                            pass

                    # -------------------------------------------------
                    # Download product
                    # -------------------------------------------------

                    kepler_products[i].download(
                        download_dir=str(TEMP_DIR)
                    )

                    # -------------------------------------------------
                    # Find THIS exact downloaded FITS
                    # -------------------------------------------------

                    downloaded_files = list(
                        TEMP_DIR.rglob(filename)
                    )

                    if not downloaded_files:
                        raise FileNotFoundError(
                            f"Downloaded FITS not found: {filename}"
                        )

                    source_path = downloaded_files[0]

                    # -------------------------------------------------
                    # Make sure the file isn't empty
                    # -------------------------------------------------

                    if source_path.stat().st_size == 0:
                        raise IOError(
                            f"Downloaded FITS is empty: {filename}"
                        )

                    # -------------------------------------------------
                    # Move to FINAL raw directory
                    # -------------------------------------------------

                    shutil.move(
                        str(source_path),
                        str(final_path)
                    )

                    # -------------------------------------------------
                    # Verify final file
                    # -------------------------------------------------

                    if not final_path.exists():
                        raise IOError(
                            f"FITS was not found after moving: {filename}"
                        )

                    products_downloaded += 1
                    success = True

                    print(
                        f"Downloaded: {filename}"
                    )

                    break

                except Exception as e:

                    print(
                        f"FAILED | KIC {kic} | "
                        f"Product {i + 1}/{products_found} | "
                        f"Attempt {attempt}: {e}"
                    )

                    # Remove only this failed temporary file
                    failed_temp_files = list(
                        TEMP_DIR.rglob(filename)
                    )

                    for failed_file in failed_temp_files:

                        try:
                            failed_file.unlink()

                        except Exception:
                            pass

                    if attempt < max_retries:
                        wait_time = 5 * attempt

                        print(
                            f"Retrying in {wait_time} seconds..."
                        )

                        time.sleep(wait_time)

            # -----------------------------------------------------
            # Product failed after all retries
            # -----------------------------------------------------

            if not success:

                failed_products += 1

                print(
                    f"PERMANENT FAILURE: {filename}"
                )

        # ---------------------------------------------------------
        # 4. Overall KIC status
        # ---------------------------------------------------------

        if failed_products == 0:
            status = "success"

        elif products_downloaded > 0:
            status = "partial"

        else:
            status = "failed"

        return {
            "kepid": kic,
            "status": status,
            "products_found": products_found,
            "products_downloaded": products_downloaded,
            "failed_products": failed_products
        }

    except Exception as e:

        print(
            f"KIC {kic} search failed: {e}"
        )

        return {
            "kepid": kic,
            "status": "search_failed",
            "products_found": 0,
            "products_downloaded": 0,
            "failed_products": 0
        }

In [17]:
test_kic = 1870398

print("Testing corrected downloader on:", test_kic)

test_result = download_kic_products(test_kic)

print("\nFINAL RESULT:")
print(test_result)

Testing corrected downloader on: 1870398
Already exists: kplr001870398-2009166043257_llc.fits
Already exists: kplr001870398-2009259160929_llc.fits
Already exists: kplr001870398-2009350155506_llc.fits
Already exists: kplr001870398-2010078095331_llc.fits
Already exists: kplr001870398-2010174085026_llc.fits
Already exists: kplr001870398-2010265121752_llc.fits
Already exists: kplr001870398-2010355172524_llc.fits
Already exists: kplr001870398-2011073133259_llc.fits
Already exists: kplr001870398-2011177032512_llc.fits
Already exists: kplr001870398-2011271113734_llc.fits
Already exists: kplr001870398-2012004120508_llc.fits
Already exists: kplr001870398-2012088054726_llc.fits
Already exists: kplr001870398-2012179063303_llc.fits
Already exists: kplr001870398-2012277125453_llc.fits
Already exists: kplr001870398-2013011073258_llc.fits
Already exists: kplr001870398-2013098041711_llc.fits
Already exists: kplr001870398-2013131215648_llc.fits

FINAL RESULT:
{'kepid': 1870398, 'status': 'success', 'products_found': 17, 'products_downloaded': 17, 'failed_products': 0}

In [18]:
fits_files = list(FITS_DIR.glob("*.fits"))

print("FITS files in final directory:", len(fits_files))

for file in fits_files[:20]:
    print(file.name)

FITS files in final directory: 41503
kplr000757450-2009166043257_llc.fits
kplr000757450-2009259160929_llc.fits
kplr000757450-2009350155506_llc.fits
kplr000757450-2010078095331_llc.fits
kplr000757450-2010174085026_llc.fits
kplr000757450-2010265121752_llc.fits
kplr000757450-2010355172524_llc.fits
kplr000757450-2011073133259_llc.fits
kplr000757450-2011177032512_llc.fits
kplr000757450-2011208035123_slc.fits
kplr000757450-2011240104155_slc.fits
kplr000757450-2011271113734_llc.fits
kplr000757450-2011271113734_slc.fits
kplr000757450-2011303113607_slc.fits
kplr000757450-2011334093404_slc.fits
kplr000757450-2012004120508_llc.fits
kplr000757450-2012004120508_slc.fits
kplr000757450-2012032013838_slc.fits
kplr000757450-2012060035710_slc.fits
kplr000757450-2012088054726_llc.fits

In [19]:
pilot_ids = jhalak_ids[:10]

pilot_results = []

for index, kic in enumerate(pilot_ids, start=1):

    print("\n" + "=" * 70)
    print(f"[{index}/10] Processing KIC {kic}")
    print("=" * 70)

    result = download_kic_products(kic)

    pilot_results.append(result)

    print("Result:", result)

======================================================================
[1/10] Processing KIC 757450
======================================================================

Already exists: kplr000757450-2009166043257_llc.fits
Already exists: kplr000757450-2009259160929_llc.fits
Already exists: kplr000757450-2009350155506_llc.fits
Already exists: kplr000757450-2010078095331_llc.fits
Already exists: kplr000757450-2010174085026_llc.fits
Already exists: kplr000757450-2010265121752_llc.fits
Already exists: kplr000757450-2010355172524_llc.fits
Already exists: kplr000757450-2011271113734_slc.fits
Already exists: kplr000757450-2011240104155_slc.fits
Already exists: kplr000757450-2011208035123_slc.fits
Already exists: kplr000757450-2011334093404_slc.fits
Already exists: kplr000757450-2011303113607_slc.fits
Already exists: kplr000757450-2011073133259_llc.fits
Already exists: kplr000757450-2011177032512_llc.fits
Already exists: kplr000757450-2011271113734_llc.fits
Already exists: kplr000757450-2012004120508_slc.fits
Already exists: kplr000757450-2012032013838_slc.fits
Already exists: kplr000757450-2012060035710_slc.fits
Already exists: kplr000757450-2012088054726_slc.fits
Already exists: kplr000757450-2012121044856_slc.fits
Already exists: kplr000757450-2012151031540_slc.fits
Already exists: kplr000757450-2012179063303_slc.fits
Already exists: kplr000757450-2012211050319_slc.fits
Already exists: kplr000757450-2012242122129_slc.fits
Already exists: kplr000757450-2012277125453_slc.fits
Already exists: kplr000757450-2012341132017_slc.fits
Already exists: kplr000757450-2012310112549_slc.fits
Already exists: kplr000757450-2012004120508_llc.fits
Already exists: kplr000757450-2012088054726_llc.fits
Already exists: kplr000757450-2012179063303_llc.fits
Already exists: kplr000757450-2012277125453_llc.fits
Already exists: kplr000757450-2013011073258_slc.fits
Already exists: kplr000757450-2013011073258_llc.fits
Already exists: kplr000757450-2013098041711_llc.fits
Already exists: kplr000757450-2013131215648_llc.fits
Result: {'kepid': 757450, 'status': 'success', 'products_found': 35, 'products_downloaded': 35, 'failed_products': 0}

======================================================================
[2/10] Processing KIC 892772
======================================================================
Already exists: kplr000892772-2010078095331_llc.fits
Already exists: kplr000892772-2010174085026_llc.fits
Already exists: kplr000892772-2010265121752_llc.fits
Already exists: kplr000892772-2010355172524_llc.fits
Already exists: kplr000892772-2011073133259_llc.fits
Already exists: kplr000892772-2011177032512_llc.fits
Already exists: kplr000892772-2011271113734_llc.fits
Already exists: kplr000892772-2012004120508_llc.fits
Already exists: kplr000892772-2012088054726_llc.fits
Already exists: kplr000892772-2012179063303_llc.fits
Already exists: kplr000892772-2012277125453_llc.fits
Already exists: kplr000892772-2013011073258_llc.fits
Already exists: kplr000892772-2013098041711_llc.fits
Already exists: kplr000892772-2013131215648_llc.fits
Result: {'kepid': 892772, 'status': 'success', 'products_found': 14, 'products_downloaded': 14, 'failed_products': 0}

======================================================================
[3/10] Processing KIC 1025986
======================================================================
Already exists: kplr001025986-2009322144938_slc.fits
Already exists: kplr001025986-2009131105131_llc.fits
Already exists: kplr001025986-2009166043257_llc.fits
Already exists: kplr001025986-2009259160929_llc.fits
Already exists: kplr001025986-2009350155506_llc.fits
Already exists: kplr001025986-2010078095331_llc.fits
Already exists: kplr001025986-2010174085026_llc.fits
Already exists: kplr001025986-2010265121752_llc.fits
Already exists: kplr001025986-2010355172524_llc.fits
Already exists: kplr001025986-2011073133259_llc.fits
Already exists: kplr001025986-2011177032512_llc.fits
Already exists: kplr001025986-2011271113734_llc.fits
Already exists: kplr001025986-2012004120508_llc.fits
Already exists: kplr001025986-2012088054726_llc.fits
Already exists: kplr001025986-2012179063303_llc.fits
Already exists: kplr001025986-2012277125453_llc.fits
Already exists: kplr001025986-2013011073258_llc.fits
Already exists: kplr001025986-2013098041711_llc.fits
Already exists: kplr001025986-2013131215648_llc.fits
Result: {'kepid': 1025986, 'status': 'success', 'products_found': 19, 'products_downloaded': 19, 'failed_products': 0}

======================================================================
[4/10] Processing KIC 1026032
======================================================================
Already exists: kplr001026032-2009166043257_llc.fits
Already exists: kplr001026032-2009259160929_llc.fits
Already exists: kplr001026032-2009350155506_llc.fits
Already exists: kplr001026032-2010078095331_llc.fits
Already exists: kplr001026032-2010174085026_llc.fits
Already exists: kplr001026032-2010265121752_llc.fits
Already exists: kplr001026032-2010355172524_llc.fits
Already exists: kplr001026032-2011073133259_llc.fits
Already exists: kplr001026032-2011177032512_llc.fits
Already exists: kplr001026032-2011271113734_llc.fits
Already exists: kplr001026032-2012004120508_llc.fits
Already exists: kplr001026032-2012088054726_llc.fits
Already exists: kplr001026032-2012179063303_llc.fits
Already exists: kplr001026032-2012277125453_llc.fits
Already exists: kplr001026032-2013011073258_llc.fits
Already exists: kplr001026032-2013098041711_llc.fits
Already exists: kplr001026032-2013131215648_llc.fits
Result: {'kepid': 1026032, 'status': 'success', 'products_found': 17, 'products_downloaded': 17, 'failed_products': 0}

======================================================================
[5/10] Processing KIC 1026957
======================================================================
Already exists: kplr001026957-2009131105131_llc.fits
Already exists: kplr001026957-2009166043257_llc.fits
Already exists: kplr001026957-2009259160929_llc.fits
Already exists: kplr001026957-2009350155506_llc.fits
Already exists: kplr001026957-2010078095331_llc.fits
Already exists: kplr001026957-2010174085026_llc.fits
Already exists: kplr001026957-2010265121752_llc.fits
Already exists: kplr001026957-2010355172524_llc.fits
Already exists: kplr001026957-2011053090032_slc.fits
Already exists: kplr001026957-2011073133259_llc.fits
Already exists: kplr001026957-2011177032512_llc.fits
Already exists: kplr001026957-2011271113734_llc.fits
Already exists: kplr001026957-2012004120508_llc.fits
Already exists: kplr001026957-2012088054726_llc.fits
Already exists: kplr001026957-2012179063303_llc.fits
Already exists: kplr001026957-2012277125453_llc.fits
Already exists: kplr001026957-2013011073258_llc.fits
Already exists: kplr001026957-2013098041711_llc.fits
Already exists: kplr001026957-2013131215648_llc.fits
Result: {'kepid': 1026957, 'status': 'success', 'products_found': 19, 'products_downloaded': 19, 'failed_products': 0}

======================================================================
[6/10] Processing KIC 1027438
======================================================================
Already exists: kplr001027438-2009166043257_llc.fits
Already exists: kplr001027438-2009259160929_llc.fits
Already exists: kplr001027438-2009350155506_llc.fits
Already exists: kplr001027438-2010078095331_llc.fits
Already exists: kplr001027438-2010174085026_llc.fits
Already exists: kplr001027438-2010265121752_llc.fits
Already exists: kplr001027438-2010355172524_llc.fits
Already exists: kplr001027438-2011208035123_slc.fits
Already exists: kplr001027438-2011073133259_llc.fits
Already exists: kplr001027438-2011177032512_llc.fits
Already exists: kplr001027438-2011271113734_llc.fits
Already exists: kplr001027438-2012004120508_llc.fits
Already exists: kplr001027438-2012088054726_llc.fits
Already exists: kplr001027438-2012179063303_llc.fits
Already exists: kplr001027438-2012277125453_llc.fits
Already exists: kplr001027438-2013011073258_llc.fits
Already exists: kplr001027438-2013098041711_llc.fits
Already exists: kplr001027438-2013131215648_llc.fits
Result: {'kepid': 1027438, 'status': 'success', 'products_found': 18, 'products_downloaded': 18, 'failed_products': 0}

======================================================================
[7/10] Processing KIC 1161345
======================================================================
Already exists: kplr001161345-2009131105131_llc.fits
Already exists: kplr001161345-2009166043257_llc.fits
Already exists: kplr001161345-2009259160929_llc.fits
Already exists: kplr001161345-2009350155506_llc.fits
Already exists: kplr001161345-2010078095331_llc.fits
Already exists: kplr001161345-2010174085026_llc.fits
Already exists: kplr001161345-2010265121752_llc.fits
Already exists: kplr001161345-2010355172524_llc.fits
Already exists: kplr001161345-2011145075126_slc.fits
Already exists: kplr001161345-2011116030358_slc.fits
Already exists: kplr001161345-2011177032512_slc.fits
Already exists: kplr001161345-2011208035123_slc.fits
Already exists: kplr001161345-2011240104155_slc.fits
Already exists: kplr001161345-2011271113734_slc.fits
Already exists: kplr001161345-2011303113607_slc.fits
Already exists: kplr001161345-2011334093404_slc.fits
Already exists: kplr001161345-2011073133259_llc.fits
Already exists: kplr001161345-2011177032512_llc.fits
Already exists: kplr001161345-2011271113734_llc.fits
Already exists: kplr001161345-2012004120508_slc.fits
Already exists: kplr001161345-2012032013838_slc.fits
Already exists: kplr001161345-2012060035710_slc.fits
Already exists: kplr001161345-2012088054726_slc.fits
Already exists: kplr001161345-2012121044856_slc.fits
Already exists: kplr001161345-2012151031540_slc.fits
Already exists: kplr001161345-2012179063303_slc.fits
Already exists: kplr001161345-2012211050319_slc.fits
Already exists: kplr001161345-2012242122129_slc.fits
Already exists: kplr001161345-2012277125453_slc.fits
Already exists: kplr001161345-2012310112549_slc.fits
Already exists: kplr001161345-2012341132017_slc.fits
Already exists: kplr001161345-2012004120508_llc.fits
Already exists: kplr001161345-2012088054726_llc.fits
Already exists: kplr001161345-2012179063303_llc.fits
Already exists: kplr001161345-2012277125453_llc.fits
Already exists: kplr001161345-2013011073258_slc.fits
Already exists: kplr001161345-2013017113907_slc.fits
Already exists: kplr001161345-2013065031647_slc.fits
Already exists: kplr001161345-2013098041711_slc.fits
Already exists: kplr001161345-2013121191144_slc.fits
Already exists: kplr001161345-2013131215648_slc.fits
Already exists: kplr001161345-2013011073258_llc.fits
Already exists: kplr001161345-2013098041711_llc.fits
Already exists: kplr001161345-2013131215648_llc.fits
Result: {'kepid': 1161345, 'status': 'success', 'products_found': 44, 'products_downloaded': 44, 'failed_products': 0}

======================================================================
[8/10] Processing KIC 1161949
======================================================================
Already exists: kplr001161949-2009166043257_llc.fits
Already exists: kplr001161949-2009259160929_llc.fits
Already exists: kplr001161949-2009350155506_llc.fits
Already exists: kplr001161949-2010078095331_llc.fits
Already exists: kplr001161949-2010174085026_llc.fits
Already exists: kplr001161949-2010265121752_llc.fits
Already exists: kplr001161949-2010355172524_llc.fits
Already exists: kplr001161949-2011073133259_llc.fits
Already exists: kplr001161949-2011177032512_llc.fits
Already exists: kplr001161949-2011271113734_llc.fits
Already exists: kplr001161949-2012004120508_llc.fits
Already exists: kplr001161949-2012088054726_llc.fits
Already exists: kplr001161949-2012179063303_llc.fits
Already exists: kplr001161949-2012277125453_llc.fits
Already exists: kplr001161949-2013011073258_llc.fits
Already exists: kplr001161949-2013098041711_llc.fits
Already exists: kplr001161949-2013131215648_llc.fits
Result: {'kepid': 1161949, 'status': 'success', 'products_found': 17, 'products_downloaded': 17, 'failed_products': 0}

======================================================================
[9/10] Processing KIC 1164301
======================================================================
Already exists: kplr001164301-2009166043257_llc.fits
Already exists: kplr001164301-2009259160929_llc.fits
Already exists: kplr001164301-2009350155506_llc.fits
Already exists: kplr001164301-2010078095331_llc.fits
Already exists: kplr001164301-2010174085026_llc.fits
Already exists: kplr001164301-2010265121752_llc.fits
Already exists: kplr001164301-2010355172524_llc.fits
Already exists: kplr001164301-2011073133259_llc.fits
Already exists: kplr001164301-2011177032512_llc.fits
Already exists: kplr001164301-2011271113734_llc.fits
Already exists: kplr001164301-2012004120508_llc.fits
Already exists: kplr001164301-2012088054726_llc.fits
Already exists: kplr001164301-2012179063303_llc.fits
Already exists: kplr001164301-2012277125453_llc.fits
Already exists: kplr001164301-2013011073258_llc.fits
Result: {'kepid': 1164301, 'status': 'success', 'products_found': 15, 'products_downloaded': 15, 'failed_products': 0}

======================================================================
[10/10] Processing KIC 1293031
======================================================================
Already exists: kplr001293031-2009131105131_llc.fits
Already exists: kplr001293031-2009166043257_llc.fits
Already exists: kplr001293031-2009259160929_llc.fits
Already exists: kplr001293031-2009350155506_llc.fits
Already exists: kplr001293031-2010078095331_llc.fits
Already exists: kplr001293031-2010174085026_llc.fits
Already exists: kplr001293031-2010265121752_llc.fits
Already exists: kplr001293031-2010355172524_llc.fits
Already exists: kplr001293031-2011073133259_llc.fits
Already exists: kplr001293031-2011177032512_llc.fits
Already exists: kplr001293031-2011271113734_llc.fits
Already exists: kplr001293031-2012004120508_llc.fits
Already exists: kplr001293031-2012088054726_llc.fits
Already exists: kplr001293031-2012179063303_llc.fits
Already exists: kplr001293031-2012277125453_llc.fits
Already exists: kplr001293031-2013011073258_llc.fits
Already exists: kplr001293031-2013098041711_llc.fits
Already exists: kplr001293031-2013131215648_llc.fits
Result: {'kepid': 1293031, 'status': 'success', 'products_found': 18, 'products_downloaded': 18, 'failed_products': 0}

In [20]:
pilot_df = pd.DataFrame(pilot_results)

display(pilot_df)

print("Total KICs:", len(pilot_df))
print("Products found:", pilot_df["products_found"].sum())
print("Products downloaded:", pilot_df["products_downloaded"].sum())
print("Products failed:", pilot_df["failed_products"].sum())

     kepid   status  products_found  products_downloaded  failed_products
0   757450  success              35                   35                0
1   892772  success              14                   14                0
2  1025986  success              19                   19                0
3  1026032  success              17                   17                0
4  1026957  success              19                   19                0
5  1027438  success              18                   18                0
6  1161345  success              44                   44                0
7  1161949  success              17                   17                0
8  1164301  success              15                   15                0
9  1293031  success              18                   18                0

Total KICs: 10
Products found: 216
Products downloaded: 216
Products failed: 0

In [21]:
import shutil
import time

print("shutil and time imported successfully")

shutil and time imported successfully

In [ ]:
all_results = []

total = len(jhalak_ids)

print(f"Starting full download for {total} KIC IDs...")

for index, kic in enumerate(jhalak_ids, start=1):

    print("\n" + "=" * 70)
    print(f"[{index}/{total}] Processing KIC {kic}")
    print("=" * 70)

    result = download_kic_products(kic)

    all_results.append(result)

    # Save progress after EVERY KIC
    progress_df = pd.DataFrame(all_results)

    progress_df.to_csv(
        METADATA_DIR / "jhalak_download_log.csv",
        index=False
    )

    print("Result:", result)

print("\n" + "=" * 70)
print("FULL DOWNLOAD FINISHED")
print("=" * 70)

final_df = pd.DataFrame(all_results)

print("KICs processed:", len(final_df))
print("\nStatus:")
print(final_df["status"].value_counts())

print("\nProducts found:",
      final_df["products_found"].sum())

print("Products downloaded:",
      final_df["products_downloaded"].sum())

print("Products failed:",
      final_df["failed_products"].sum())

Starting full download for 4107 KIC IDs...

======================================================================
[1/4107] Processing KIC 757450
======================================================================
Already exists: kplr000757450-2009166043257_llc.fits
Already exists: kplr000757450-2009259160929_llc.fits
Already exists: kplr000757450-2009350155506_llc.fits
Already exists: kplr000757450-2010078095331_llc.fits
Already exists: kplr000757450-2010174085026_llc.fits
Already exists: kplr000757450-2010265121752_llc.fits
Already exists: kplr000757450-2010355172524_llc.fits
Already exists: kplr000757450-2011271113734_slc.fits
Already exists: kplr000757450-2011240104155_slc.fits
Already exists: kplr000757450-2011208035123_slc.fits
Already exists: kplr000757450-2011334093404_slc.fits
Already exists: kplr000757450-2011303113607_slc.fits
Already exists: kplr000757450-2011073133259_llc.fits
Already exists: kplr000757450-2011177032512_llc.fits
Already exists: kplr000757450-2011271113734_llc.fits
Already exists: kplr000757450-2012004120508_slc.fits
Already exists: kplr000757450-2012032013838_slc.fits
Already exists: kplr000757450-2012060035710_slc.fits
Already exists: kplr000757450-2012088054726_slc.fits
Already exists: kplr000757450-2012121044856_slc.fits
Already exists: kplr000757450-2012151031540_slc.fits
Already exists: kplr000757450-2012179063303_slc.fits
Already exists: kplr000757450-2012211050319_slc.fits
Already exists: kplr000757450-2012242122129_slc.fits
Already exists: kplr000757450-2012277125453_slc.fits
Already exists: kplr000757450-2012341132017_slc.fits
Already exists: kplr000757450-2012310112549_slc.fits
Already exists: kplr000757450-2012004120508_llc.fits
Already exists: kplr000757450-2012088054726_llc.fits
Already exists: kplr000757450-2012179063303_llc.fits
Already exists: kplr000757450-2012277125453_llc.fits
Already exists: kplr000757450-2013011073258_slc.fits
Already exists: kplr000757450-2013011073258_llc.fits
Already exists: kplr000757450-2013098041711_llc.fits
Already exists: kplr000757450-2013131215648_llc.fits
Result: {'kepid': 757450, 'status': 'success', 'products_found': 35, 'products_downloaded': 35, 'failed_products': 0}

======================================================================
[2/4107] Processing KIC 892772
======================================================================
Already exists: kplr000892772-2010078095331_llc.fits
Already exists: kplr000892772-2010174085026_llc.fits
Already exists: kplr000892772-2010265121752_llc.fits
Already exists: kplr000892772-2010355172524_llc.fits
Already exists: kplr000892772-2011073133259_llc.fits
Already exists: kplr000892772-2011177032512_llc.fits
Already exists: kplr000892772-2011271113734_llc.fits
Already exists: kplr000892772-2012004120508_llc.fits
Already exists: kplr000892772-2012088054726_llc.fits
Already exists: kplr000892772-2012179063303_llc.fits
Already exists: kplr000892772-2012277125453_llc.fits
Already exists: kplr000892772-2013011073258_llc.fits
Already exists: kplr000892772-2013098041711_llc.fits
Already exists: kplr000892772-2013131215648_llc.fits
Result: {'kepid': 892772, 'status': 'success', 'products_found': 14, 'products_downloaded': 14, 'failed_products': 0}

======================================================================
[3/4107] Processing KIC 1025986
======================================================================
Already exists: kplr001025986-2009322144938_slc.fits
Already exists: kplr001025986-2009131105131_llc.fits
Already exists: kplr001025986-2009166043257_llc.fits
Already exists: kplr001025986-2009259160929_llc.fits
Already exists: kplr001025986-2009350155506_llc.fits
Already exists: kplr001025986-2010078095331_llc.fits
Already exists: kplr001025986-2010174085026_llc.fits
Already exists: kplr001025986-2010265121752_llc.fits
Already exists: kplr001025986-2010355172524_llc.fits
Already exists: kplr001025986-2011073133259_llc.fits
Already exists: kplr001025986-2011177032512_llc.fits
Already exists: kplr001025986-2011271113734_llc.fits
Already exists: kplr001025986-2012004120508_llc.fits
Already exists: kplr001025986-2012088054726_llc.fits
Already exists: kplr001025986-2012179063303_llc.fits
Already exists: kplr001025986-2012277125453_llc.fits
Already exists: kplr001025986-2013011073258_llc.fits
Already exists: kplr001025986-2013098041711_llc.fits
Already exists: kplr001025986-2013131215648_llc.fits
Result: {'kepid': 1025986, 'status': 'success', 'products_found': 19, 'products_downloaded': 19, 'failed_products': 0}

======================================================================
[4/4107] Processing KIC 1026032
======================================================================
Already exists: kplr001026032-2009166043257_llc.fits
Already exists: kplr001026032-2009259160929_llc.fits
Already exists: kplr001026032-2009350155506_llc.fits
Already exists: kplr001026032-2010078095331_llc.fits
Already exists: kplr001026032-2010174085026_llc.fits
Already exists: kplr001026032-2010265121752_llc.fits
Already exists: kplr001026032-2010355172524_llc.fits
Already exists: kplr001026032-2011073133259_llc.fits
Already exists: kplr001026032-2011177032512_llc.fits
Already exists: kplr001026032-2011271113734_llc.fits
Already exists: kplr001026032-2012004120508_llc.fits
Already exists: kplr001026032-2012088054726_llc.fits
Already exists: kplr001026032-2012179063303_llc.fits
Already exists: kplr001026032-2012277125453_llc.fits
Already exists: kplr001026032-2013011073258_llc.fits
Already exists: kplr001026032-2013098041711_llc.fits
Already exists: kplr001026032-2013131215648_llc.fits
Result: {'kepid': 1026032, 'status': 'success', 'products_found': 17, 'products_downloaded': 17, 'failed_products': 0}

======================================================================
[5/4107] Processing KIC 1026957
======================================================================
Already exists: kplr001026957-2009131105131_llc.fits
Already exists: kplr001026957-2009166043257_llc.fits
Already exists: kplr001026957-2009259160929_llc.fits
Already exists: kplr001026957-2009350155506_llc.fits
Already exists: kplr001026957-2010078095331_llc.fits
Already exists: kplr001026957-2010174085026_llc.fits
Already exists: kplr001026957-2010265121752_llc.fits
Already exists: kplr001026957-2010355172524_llc.fits
Already exists: kplr001026957-2011053090032_slc.fits
Already exists: kplr001026957-2011073133259_llc.fits
Already exists: kplr001026957-2011177032512_llc.fits
Already exists: kplr001026957-2011271113734_llc.fits
Already exists: kplr001026957-2012004120508_llc.fits
Already exists: kplr001026957-2012088054726_llc.fits
Already exists: kplr001026957-2012179063303_llc.fits
Already exists: kplr001026957-2012277125453_llc.fits
Already exists: kplr001026957-2013011073258_llc.fits
Already exists: kplr001026957-2013098041711_llc.fits
Already exists: kplr001026957-2013131215648_llc.fits
Result: {'kepid': 1026957, 'status': 'success', 'products_found': 19, 'products_downloaded': 19, 'failed_products': 0}

======================================================================
[6/4107] Processing KIC 1027438
======================================================================
Already exists: kplr001027438-2009166043257_llc.fits
Already exists: kplr001027438-2009259160929_llc.fits
Already exists: kplr001027438-2009350155506_llc.fits
Already exists: kplr001027438-2010078095331_llc.fits
Already exists: kplr001027438-2010174085026_llc.fits
Already exists: kplr001027438-2010265121752_llc.fits
Already exists: kplr001027438-2010355172524_llc.fits
Already exists: kplr001027438-2011208035123_slc.fits
Already exists: kplr001027438-2011073133259_llc.fits
Already exists: kplr001027438-2011177032512_llc.fits
Already exists: kplr001027438-2011271113734_llc.fits
Already exists: kplr001027438-2012004120508_llc.fits
Already exists: kplr001027438-2012088054726_llc.fits
Already exists: kplr001027438-2012179063303_llc.fits
Already exists: kplr001027438-2012277125453_llc.fits
Already exists: kplr001027438-2013011073258_llc.fits
Already exists: kplr001027438-2013098041711_llc.fits
Already exists: kplr001027438-2013131215648_llc.fits
Result: {'kepid': 1027438, 'status': 'success', 'products_found': 18, 'products_downloaded': 18, 'failed_products': 0}

======================================================================
[7/4107] Processing KIC 1161345
======================================================================
Already exists: kplr001161345-2009131105131_llc.fits
Already exists: kplr001161345-2009166043257_llc.fits
Already exists: kplr001161345-2009259160929_llc.fits
Already exists: kplr001161345-2009350155506_llc.fits
Already exists: kplr001161345-2010078095331_llc.fits
Already exists: kplr001161345-2010174085026_llc.fits
Already exists: kplr001161345-2010265121752_llc.fits
Already exists: kplr001161345-2010355172524_llc.fits
Already exists: kplr001161345-2011145075126_slc.fits
Already exists: kplr001161345-2011116030358_slc.fits
Already exists: kplr001161345-2011177032512_slc.fits
Already exists: kplr001161345-2011208035123_slc.fits
Already exists: kplr001161345-2011240104155_slc.fits
Already exists: kplr001161345-2011271113734_slc.fits
Already exists: kplr001161345-2011303113607_slc.fits
Already exists: kplr001161345-2011334093404_slc.fits
Already exists: kplr001161345-2011073133259_llc.fits
Already exists: kplr001161345-2011177032512_llc.fits
Already exists: kplr001161345-2011271113734_llc.fits
Already exists: kplr001161345-2012004120508_slc.fits
Already exists: kplr001161345-2012032013838_slc.fits
Already exists: kplr001161345-2012060035710_slc.fits
Already exists: kplr001161345-2012088054726_slc.fits
Already exists: kplr001161345-2012121044856_slc.fits
Already exists: kplr001161345-2012151031540_slc.fits
Already exists: kplr001161345-2012179063303_slc.fits
Already exists: kplr001161345-2012211050319_slc.fits
Already exists: kplr001161345-2012242122129_slc.fits
Already exists: kplr001161345-2012277125453_slc.fits
Already exists: kplr001161345-2012310112549_slc.fits
Already exists: kplr001161345-2012341132017_slc.fits
Already exists: kplr001161345-2012004120508_llc.fits
Already exists: kplr001161345-2012088054726_llc.fits
Already exists: kplr001161345-2012179063303_llc.fits
Already exists: kplr001161345-2012277125453_llc.fits
Already exists: kplr001161345-2013011073258_slc.fits
Already exists: kplr001161345-2013017113907_slc.fits
Already exists: kplr001161345-2013065031647_slc.fits
Already exists: kplr001161345-2013098041711_slc.fits
Already exists: kplr001161345-2013121191144_slc.fits
Already exists: kplr001161345-2013131215648_slc.fits
Already exists: kplr001161345-2013011073258_llc.fits
Already exists: kplr001161345-2013098041711_llc.fits
Already exists: kplr001161345-2013131215648_llc.fits
Result: {'kepid': 1161345, 'status': 'success', 'products_found': 44, 'products_downloaded': 44, 'failed_products': 0}

======================================================================
[8/4107] Processing KIC 1161949
======================================================================
Already exists: kplr001161949-2009166043257_llc.fits
Already exists: kplr001161949-2009259160929_llc.fits
Already exists: kplr001161949-2009350155506_llc.fits
Already exists: kplr001161949-2010078095331_llc.fits
Already exists: kplr001161949-2010174085026_llc.fits
Already exists: kplr001161949-2010265121752_llc.fits
Already exists: kplr001161949-2010355172524_llc.fits
Already exists: kplr001161949-2011073133259_llc.fits
Already exists: kplr001161949-2011177032512_llc.fits
Already exists: kplr001161949-2011271113734_llc.fits
Already exists: kplr001161949-2012004120508_llc.fits
Already exists: kplr001161949-2012088054726_llc.fits
Already exists: kplr001161949-2012179063303_llc.fits
Already exists: kplr001161949-2012277125453_llc.fits
Already exists: kplr001161949-2013011073258_llc.fits
Already exists: kplr001161949-2013098041711_llc.fits
Already exists: kplr001161949-2013131215648_llc.fits
Result: {'kepid': 1161949, 'status': 'success', 'products_found': 17, 'products_downloaded': 17, 'failed_products': 0}

======================================================================
[9/4107] Processing KIC 1164301
======================================================================
Already exists: kplr001164301-2009166043257_llc.fits
Already exists: kplr001164301-2009259160929_llc.fits
Already exists: kplr001164301-2009350155506_llc.fits
Already exists: kplr001164301-2010078095331_llc.fits
Already exists: kplr001164301-2010174085026_llc.fits
Already exists: kplr001164301-2010265121752_llc.fits
Already exists: kplr001164301-2010355172524_llc.fits
Already exists: kplr001164301-2011073133259_llc.fits
Already exists: kplr001164301-2011177032512_llc.fits
Already exists: kplr001164301-2011271113734_llc.fits
Already exists: kplr001164301-2012004120508_llc.fits
Already exists: kplr001164301-2012088054726_llc.fits
Already exists: kplr001164301-2012179063303_llc.fits
Already exists: kplr001164301-2012277125453_llc.fits
Already exists: kplr001164301-2013011073258_llc.fits
Result: {'kepid': 1164301, 'status': 'success', 'products_found': 15, 'products_downloaded': 15, 'failed_products': 0}

======================================================================
[10/4107] Processing KIC 1293031
======================================================================
Already exists: kplr001293031-2009131105131_llc.fits
Already exists: kplr001293031-2009166043257_llc.fits
Already exists: kplr001293031-2009259160929_llc.fits
Already exists: kplr001293031-2009350155506_llc.fits
Already exists: kplr001293031-2010078095331_llc.fits
Already exists: kplr001293031-2010174085026_llc.fits
Already exists: kplr001293031-2010265121752_llc.fits
Already exists: kplr001293031-2010355172524_llc.fits
Already exists: kplr001293031-2011073133259_llc.fits
Already exists: kplr001293031-2011177032512_llc.fits
Already exists: kplr001293031-2011271113734_llc.fits
Already exists: kplr001293031-2012004120508_llc.fits
Already exists: kplr001293031-2012088054726_llc.fits
Already exists: kplr001293031-2012179063303_llc.fits
Already exists: kplr001293031-2012277125453_llc.fits
Already exists: kplr001293031-2013011073258_llc.fits
Already exists: kplr001293031-2013098041711_llc.fits
Already exists: kplr001293031-2013131215648_llc.fits
Result: {'kepid': 1293031, 'status': 'success', 'products_found': 18, 'products_downloaded': 18, 'failed_products': 0}

======================================================================
[11/4107] Processing KIC 1293046
======================================================================
Already exists: kplr001293046-2009166043257_llc.fits
Already exists: kplr001293046-2009259160929_llc.fits
Already exists: kplr001293046-2009350155506_llc.fits
Already exists: kplr001293046-2010078095331_llc.fits
Already exists: kplr001293046-2010174085026_llc.fits
Already exists: kplr001293046-2010265121752_llc.fits
Already exists: kplr001293046-2010355172524_llc.fits
Already exists: kplr001293046-2011073133259_llc.fits
Already exists: kplr001293046-2011177032512_llc.fits
Already exists: kplr001293046-2011271113734_llc.fits
Already exists: kplr001293046-2012004120508_llc.fits
Already exists: kplr001293046-2012088054726_llc.fits
Already exists: kplr001293046-2012179063303_llc.fits
Already exists: kplr001293046-2012277125453_llc.fits
Already exists: kplr001293046-2013011073258_llc.fits
Already exists: kplr001293046-2013098041711_llc.fits
Already exists: kplr001293046-2013131215648_llc.fits
Result: {'kepid': 1293046, 'status': 'success', 'products_found': 17, 'products_downloaded': 17, 'failed_products': 0}

======================================================================
[12/4107] Processing KIC 1293379
======================================================================
Already exists: kplr001293379-2010078095331_llc.fits
Already exists: kplr001293379-2010174085026_llc.fits
Already exists: kplr001293379-2010265121752_llc.fits
Already exists: kplr001293379-2010355172524_llc.fits
Already exists: kplr001293379-2011073133259_llc.fits
Already exists: kplr001293379-2011177032512_llc.fits
Already exists: kplr001293379-2011271113734_llc.fits
Already exists: kplr001293379-2012004120508_llc.fits
Already exists: kplr001293379-2012088054726_llc.fits
Already exists: kplr001293379-2012179063303_llc.fits
Already exists: kplr001293379-2012277125453_llc.fits
Already exists: kplr001293379-2013011073258_llc.fits
Already exists: kplr001293379-2013098041711_llc.fits
Already exists: kplr001293379-2013131215648_llc.fits
Result: {'kepid': 1293379, 'status': 'success', 'products_found': 14, 'products_downloaded': 14, 'failed_products': 0}

======================================================================
[13/4107] Processing KIC 1297263
======================================================================
Already exists: kplr001297263-2009350155506_llc.fits
Already exists: kplr001297263-2010078095331_llc.fits
Already exists: kplr001297263-2010355172524_llc.fits
Already exists: kplr001297263-2011073133259_llc.fits
Already exists: kplr001297263-2012004120508_llc.fits
Already exists: kplr001297263-2012088054726_llc.fits
Already exists: kplr001297263-2013011073258_llc.fits
Already exists: kplr001297263-2013098041711_llc.fits
Result: {'kepid': 1297263, 'status': 'success', 'products_found': 8, 'products_downloaded': 8, 'failed_products': 0}

======================================================================
[14/4107] Processing KIC 1429589
======================================================================
Already exists: kplr001429589-2009166043257_llc.fits
Already exists: kplr001429589-2009259160929_llc.fits
Already exists: kplr001429589-2009350155506_llc.fits
Already exists: kplr001429589-2010078095331_llc.fits
Already exists: kplr001429589-2010174085026_llc.fits
Already exists: kplr001429589-2010265121752_llc.fits
Already exists: kplr001429589-2010355172524_llc.fits
Already exists: kplr001429589-2011073133259_llc.fits
Already exists: kplr001429589-2011177032512_llc.fits
Already exists: kplr001429589-2011271113734_llc.fits
Already exists: kplr001429589-2012004120508_llc.fits
Already exists: kplr001429589-2012088054726_llc.fits
Already exists: kplr001429589-2012179063303_llc.fits
Already exists: kplr001429589-2012277125453_llc.fits
Already exists: kplr001429589-2013011073258_llc.fits
Already exists: kplr001429589-2013098041711_llc.fits
Already exists: kplr001429589-2013131215648_llc.fits
Result: {'kepid': 1429589, 'status': 'success', 'products_found': 17, 'products_downloaded': 17, 'failed_products': 0}

======================================================================
[15/4107] Processing KIC 1430305
======================================================================
Already exists: kplr001430305-2009131105131_llc.fits
Already exists: kplr001430305-2009166043257_llc.fits
Already exists: kplr001430305-2009259160929_llc.fits
Already exists: kplr001430305-2009350155506_llc.fits
Already exists: kplr001430305-2010078095331_llc.fits
Already exists: kplr001430305-2010174085026_llc.fits
Already exists: kplr001430305-2010265121752_llc.fits
Already exists: kplr001430305-2010355172524_llc.fits
Already exists: kplr001430305-2011073133259_llc.fits
Already exists: kplr001430305-2011177032512_llc.fits
Already exists: kplr001430305-2011271113734_llc.fits
Already exists: kplr001430305-2012004120508_llc.fits
Already exists: kplr001430305-2012088054726_llc.fits
Already exists: kplr001430305-2012179063303_llc.fits
Already exists: kplr001430305-2012277125453_llc.fits
Already exists: kplr001430305-2013011073258_llc.fits
Already exists: kplr001430305-2013098041711_llc.fits
Already exists: kplr001430305-2013131215648_llc.fits
Result: {'kepid': 1430305, 'status': 'success', 'products_found': 18, 'products_downloaded': 18, 'failed_products': 0}

======================================================================
[16/4107] Processing KIC 1431122
======================================================================